### ISSUE TITLE
Continuing to try to compile fib.c on Ubuntu 20.04 per the documentation

### ISSUE THREAD

**Issue by dcurtisatmit** [OpenCilk/www.opencilk.org#39] opened 2022-06-15 19:43 UTC
ubuntu@...:~/opencilk/OpenCilk-12.0.0-Linux/dcurtis$ ../bin/clang -fopencilk -O3 fib.c -o fib
/usr/bin/ld: cannot find crtbegin.o: No such file or directory
/usr/bin/ld: cannot find -lgcc
/usr/bin/ld: cannot find -lgcc_s
clang-12: error: linker command failed with exit code 1 (use -v to see invocation)

Looks like gcc needs to be installed???

**Comment by behoppe** [comment] 2022-06-15 21:30
Thanks @dcurtisatmit. Do you think it makes sense to merge this with #38? It seems like there is a single overarching issue.

Also, just to confirm, I think this is a website issue because you are following instructions from the "Getting started" page, right? Please let me know if you think this issue extends beyond errors in our documentation.

**Comment by behoppe** [comment] 2022-06-20 19:56
Thanks, @dcurtisatmit. I understand this issue and #38 are about a problem with the "Getting started" page, and that installing libc6-dev and gcc fixes the problem. 

I am not sure what you're looking at on the infrastructure repository that makes it seem like the problem is with the website and not also in that repository. Could you please clarify?

It looks to me like Getting started (and/or Install) fails to mention dependencies or prerequisites (such as libc6-dev and gcc). Would you agree that fixing the documentation probably looks something like adding a list of dependencies, and not telling people to execute "apt-get install libc6-dev" and "apt install gcc"?

Thanks for your help improving the documentation.

**Comment by behoppe** [comment] 2022-06-28 20:26
Merging this with #59 and closing.

**Closed by behoppe** 2022-06-28 20:26 UTC
